import type { FieldMapping, ContentType } from '@/features/delivery-method/types'

/**
 * Generate request body template based on field mappings and content type
 */
export function generateRequestBody(
  mappings: FieldMapping[],
  contentType: ContentType
): string {
  if (mappings.length === 0) {
    return getEmptyTemplate(contentType)
  }

  switch (contentType) {
    case 'application/json':
    case 'default':
      return generateJsonTemplate(mappings)

    case 'application/xml':
    case 'text/xml':
    case 'application/soap+xml':
      return generateXmlTemplate(mappings)

    case 'application/x-www-form-urlencoded':
      return generateUrlEncodedTemplate(mappings)

    default:
      return generateJsonTemplate(mappings) // Fallback to JSON
  }
}

/**
 * Generate JSON template with field tags
 */
function generateJsonTemplate(mappings: FieldMapping[]): string {
  const obj: Record<string, string> = {}

  mappings.forEach(mapping => {
    // Use buyer's field name as key, mapped field as value tag
    obj[mapping.name] = `[${mapping.mappedTo}]`
  })

  return JSON.stringify(obj, null, 2)
}

/**
 * Generate XML template with field tags
 */
function generateXmlTemplate(mappings: FieldMapping[]): string {
  const fields = mappings
    .map(mapping => {
      const tagName = sanitizeXmlTagName(mapping.name)
      return `  <${tagName}>[${mapping.mappedTo}]</${tagName}>`
    })
    .join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>\n<request>\n${fields}\n</request>`
}

/**
 * Generate URL-encoded template with field tags
 */
function generateUrlEncodedTemplate(mappings: FieldMapping[]): string {
  return mappings
    .map(mapping => {
      const key = encodeURIComponent(mapping.name)
      const value = `[${mapping.mappedTo}]`
      return `${key}=${value}`
    })
    .join('&')
}

/**
 * Get empty template for content type
 */
function getEmptyTemplate(contentType: ContentType): string {
  switch (contentType) {
    case 'application/json':
    case 'default':
      return '{}'

    case 'application/xml':
    case 'text/xml':
    case 'application/soap+xml':
      return '<?xml version="1.0" encoding="UTF-8"?>\n<request>\n</request>'

    case 'application/x-www-form-urlencoded':
      return ''

    default:
      return '{}'
  }
}

/**
 * Sanitize XML tag names (remove spaces, special chars)
 */
function sanitizeXmlTagName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9_-]/g, '_') // Replace invalid chars with underscore
    .replace(/^[0-9]/, '_$&') // Prepend underscore if starts with number
}

/**
 * Check if request body appears to be auto-generated (hasn't been manually edited)
 */
export function isAutoGeneratedBody(body: string, mappings: FieldMapping[], contentType: ContentType): boolean {
  if (!body.trim()) return true

  const expectedBody = generateRequestBody(mappings, contentType)

  // Normalize whitespace for comparison
  const normalizedBody = body.replace(/\s+/g, ' ').trim()
  const normalizedExpected = expectedBody.replace(/\s+/g, ' ').trim()

  return normalizedBody === normalizedExpected
}

/**
 * Generate sample data for testing (replaces field tags with mock values)
 */
export function generateSampleRequestBody(
  mappings: FieldMapping[],
  contentType: ContentType
): string {
  const template = generateRequestBody(mappings, contentType)

  // Replace field tags with test values or mock data
  let result = template
  mappings.forEach(mapping => {
    const tag = `[${mapping.mappedTo}]`
    const sampleValue = mapping.testValue || getMockValue(mapping.mappedTo)
    result = result.replaceAll(tag, sampleValue)
  })

  return result
}

/**
 * Get mock value based on field name
 */
function getMockValue(fieldName: string): string {
  // Simple mock data based on field name patterns
  if (fieldName.includes('email')) return 'test@example.com'
  if (fieldName.includes('phone')) return '555-0123'
  if (fieldName.includes('first_name')) return 'John'
  if (fieldName.includes('last_name')) return 'Doe'
  if (fieldName.includes('zip') || fieldName.includes('postal')) return '90210'
  if (fieldName.includes('city')) return 'Los Angeles'
  if (fieldName.includes('state')) return 'CA'
  if (fieldName.includes('ip')) return '192.168.1.1'
  if (fieldName.includes('address')) return '123 Main St'
  if (fieldName.includes('age') || fieldName.includes('score')) return '35'
  if (fieldName.includes('price') || fieldName.includes('amount') || fieldName.includes('income')) return '100000'
  if (fieldName.includes('date') || fieldName.includes('timestamp')) return new Date().toISOString()
  if (fieldName.includes('id')) return 'abc123'
  if (fieldName.includes('consent') || fieldName.includes('flag')) return 'true'

  return 'sample_value'
}
