/**
 * EXAMPLE: Enhanced Request Body Settings with Auto-Population
 *
 * This shows how to integrate the auto-populate feature into the existing component.
 * Replace the current request-body-settings.tsx with this version.
 */

import { useRef, useMemo, useState, useCallback } from 'react'
import { useDeliveryMethodStore } from '@/features/delivery-method/store'
import { CodeEditor, type CodeEditorHandle } from '@/components/code-editor'
import type { InsertableField } from '@/components/code-editor'
import { useAutoPopulateRequestBody } from '@/hooks/use-auto-populate-body'
import { RequestBodyToolbar } from './request-body-toolbar'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Button } from '@/components/ui/button'
import { Plus } from 'lucide-react'

interface RequestBodySettingsProps {
  phase: 'ping' | 'post'
}

export function RequestBodySettings({ phase }: RequestBodySettingsProps) {
  const isPing = phase === 'ping'

  const config = useDeliveryMethodStore((s) => s.config)
  const pingBody = config.ping.requestBody.body
  const postBody = config.post.requestBody.body
  const updatePingRequestBody = useDeliveryMethodStore((s) => s.updatePingRequestBody)
  const updatePostRequestBody = useDeliveryMethodStore((s) => s.updatePostRequestBody)
  const getPingMappedFields = useDeliveryMethodStore((s) => s.getPingMappedFields)
  const getPostMappedFields = useDeliveryMethodStore((s) => s.getPostMappedFields)

  const body = isPing ? pingBody : postBody
  const updateBody = isPing ? updatePingRequestBody : updatePostRequestBody

  // Auto-populate hook - generates template when mappings/content-type change
  const { isManuallyEdited, resetToAutoGenerated } = useAutoPopulateRequestBody(phase, {
    enabled: true, // Set to false to disable auto-populate
  })

  const editorRef = useRef<CodeEditorHandle>(null)
  const [selectedField, setSelectedField] = useState<string>('')

  const mappedFields = useMemo(() => {
    return isPing ? getPingMappedFields() : getPostMappedFields()
  }, [isPing, getPingMappedFields, getPostMappedFields])

  const mappings = isPing ? config.ping.mappings.mappings : config.post.mappings.mappings

  const contentType = isPing
    ? config.ping.urlEndpoint.contentType
    : (config.post.urlEndpoint.contentTypeSameAsPing
        ? config.ping.urlEndpoint.contentType
        : config.post.urlEndpoint.contentType)

  const insertableFields: InsertableField[] = useMemo(() => {
    return mappedFields.map((f) => ({
      tag: f.name,
      label: f.mappedTo,
      category: f.source === 'ping' ? 'PING Fields' : 'POST Fields',
    }))
  }, [mappedFields])

  const handleInsert = useCallback(() => {
    if (selectedField) {
      editorRef.current?.insertField(selectedField)
      setSelectedField('')
    }
  }, [selectedField])

  return (
    <div className="absolute inset-0 flex flex-col">
      {/* Toolbar showing auto-generate status */}
      <RequestBodyToolbar
        phase={phase}
        mappings={mappings}
        contentType={contentType}
        currentBody={body}
        isAutoGenerated={!isManuallyEdited}
        onReset={resetToAutoGenerated}
        onUpdate={updateBody}
      />

      {/* Field insertion controls */}
      <div className="flex items-center p-3 bg-background border-b border-border">
        <div className="flex-1">
          <Select value={selectedField} onValueChange={setSelectedField}>
            <SelectTrigger className="rounded-r-none border-r-0">
              <SelectValue placeholder="-- Select mapping to insert --" />
            </SelectTrigger>
            <SelectContent>
              {mappedFields.map((f) => (
                <SelectItem key={f.id} value={f.name}>
                  {f.name} → [{f.mappedTo}]
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <Button
          size="icon"
          className="rounded-l-none shrink-0"
          onClick={handleInsert}
          disabled={!selectedField}
        >
          <Plus className="h-4 w-4" />
        </Button>
      </div>

      {/* Code editor */}
      <div className="flex-1 min-h-0">
        <CodeEditor
          ref={editorRef}
          value={body}
          onChange={updateBody}
          insertableFields={insertableFields}
          className="rounded-none border-x-0 border-b-0"
        />
      </div>
    </div>
  )
}
