import { useEffect, useRef } from 'react'
import { useDeliveryMethodStore } from '@/features/delivery-method/store'
import { generateRequestBody, isAutoGeneratedBody } from '@/lib/request-body-generator'
import type { ContentType } from '@/features/delivery-method/types'

/**
 * Hook to auto-populate request body when mappings or content-type change
 * Only updates if body hasn't been manually edited
 */
export function useAutoPopulateRequestBody(
  phase: 'ping' | 'post',
  options: {
    enabled?: boolean // Allow disabling auto-populate
  } = {}
) {
  const { enabled = true } = options

  const config = useDeliveryMethodStore(s => s.config)
  const updatePingRequestBody = useDeliveryMethodStore(s => s.updatePingRequestBody)
  const updatePostRequestBody = useDeliveryMethodStore(s => s.updatePostRequestBody)

  // Track if user has manually edited the body
  const isManuallyEditedRef = useRef(false)
  const previousBodyRef = useRef('')

  const mappings = phase === 'ping'
    ? config.ping.mappings.mappings
    : config.post.mappings.mappings

  const contentType: ContentType = phase === 'ping'
    ? config.ping.urlEndpoint.contentType
    : (config.post.urlEndpoint.contentTypeSameAsPing
        ? config.ping.urlEndpoint.contentType
        : config.post.urlEndpoint.contentType)

  const currentBody = phase === 'ping'
    ? config.ping.requestBody.body
    : config.post.requestBody.body

  const updateBody = phase === 'ping' ? updatePingRequestBody : updatePostRequestBody

  useEffect(() => {
    if (!enabled) return

    // Check if body was manually edited
    if (previousBodyRef.current && previousBodyRef.current !== currentBody) {
      const wasAutoGenerated = isAutoGeneratedBody(
        previousBodyRef.current,
        mappings,
        contentType
      )
      if (!wasAutoGenerated) {
        isManuallyEditedRef.current = true
      }
    }

    previousBodyRef.current = currentBody

    // Don't auto-update if user has manually edited
    if (isManuallyEditedRef.current) return

    // Generate new body based on current mappings and content type
    const newBody = generateRequestBody(mappings, contentType)

    // Only update if different
    if (newBody !== currentBody) {
      updateBody(newBody)
    }
  }, [mappings, contentType, currentBody, updateBody, enabled])

  // Function to reset to auto-generated (useful for "Reset" button)
  const resetToAutoGenerated = () => {
    isManuallyEditedRef.current = false
    const newBody = generateRequestBody(mappings, contentType)
    updateBody(newBody)
  }

  return {
    isManuallyEdited: isManuallyEditedRef.current,
    resetToAutoGenerated,
  }
}
