import { Button } from '@/components/ui/button'
import { RotateCcw, Sparkles, TestTube } from 'lucide-react'
import { generateSampleRequestBody } from '@/lib/request-body-generator'
import type { FieldMapping, ContentType } from '@/features/delivery-method/types'

interface RequestBodyToolbarProps {
  phase: 'ping' | 'post'
  mappings: FieldMapping[]
  contentType: ContentType
  currentBody: string
  isAutoGenerated: boolean
  onReset: () => void
  onUpdate: (body: string) => void
}

export function RequestBodyToolbar({
  phase,
  mappings,
  contentType,
  currentBody,
  isAutoGenerated,
  onReset,
  onUpdate,
}: RequestBodyToolbarProps) {
  const handleGenerateSample = () => {
    const sampleBody = generateSampleRequestBody(mappings, contentType)
    onUpdate(sampleBody)
  }

  return (
    <div className="flex items-center justify-between gap-2 p-2 bg-muted/30 border-b border-border">
      <div className="flex items-center gap-2">
        {isAutoGenerated ? (
          <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <Sparkles className="h-3.5 w-3.5 text-primary" />
            <span>Auto-generated from field mappings</span>
          </div>
        ) : (
          <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <span>Manually edited</span>
          </div>
        )}
      </div>

      <div className="flex items-center gap-2">
        {!isAutoGenerated && (
          <Button
            variant="outline"
            size="sm"
            onClick={onReset}
            className="h-7 text-xs"
          >
            <RotateCcw className="h-3 w-3 mr-1.5" />
            Reset to Auto-generated
          </Button>
        )}

        <Button
          variant="outline"
          size="sm"
          onClick={handleGenerateSample}
          className="h-7 text-xs"
        >
          <TestTube className="h-3 w-3 mr-1.5" />
          Preview with Sample Data
        </Button>
      </div>
    </div>
  )
}
